### ISSUE TITLE
Fix breakpoints (don't work in IE) and check app in IE

### ISSUE THREAD

**Issue by nadezhdakharchuk** [fs/react-next-base#125]
# Summary

**Comment by Ivan-Starikov** [comment]
Used IE devtools to check breakpoints. Everything is fine. But I'm not sure we can trust it. It works really weird. 
<img width="516" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/69046400/123240868-5dbbf680-d4e9-11eb-909e-75fe8674f416.png">
